console.log("页面加载开始 0%···");
console.log("10%···");
console.log("20%···");
console.log("30%···");
console.log("40%···");
console.log("50%···");
console.log("60%···");
console.log("70%···");
console.log("80%···");
console.log("90%···");
console.log("页面加载完成 100%···");
